FROM maven as builder
WORKDIR /app
COPY pom.xml .
RUN mvn clean verify --fail-never
COPY . .
RUN mvn compile package


FROM openjdk:8-jre-alpine3.7 as production
WORKDIR /app
COPY --from=builder /app/target/metadata-service.jar /app
ENTRYPOINT ["java", "-jar", "/app/metadata-service.jar"]

